/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueva.vistas;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import prueva.mdoelo.Alumno;
import prueva.mdoelo.AlumnoData;
import prueva.mdoelo.Conexion;
import prueva.mdoelo.Cursada;
import prueva.mdoelo.CursadaData;
import prueva.mdoelo.Materia;

/**
 *
 * @author programador
 */
public class CargarNotas extends javax.swing.JInternalFrame {
private DefaultTableModel modelo;
private ArrayList<Cursada> listaCursada;
private ArrayList<Materia> listaMateria;
private CursadaData cursadaData;
private AlumnoData alumnoData;
private ArrayList<Alumno> listaAlumno;
private Conexion conexion;


    /**
     * Creates new form CargarNotas
     */
    public CargarNotas() {
    try {
        initComponents();
        
        conexion = new Conexion();
        
        modelo = new DefaultTableModel();
        
        cursadaData = new CursadaData(conexion);
        
        listaCursada = (ArrayList)cursadaData.obtenerCursadas();
        alumnoData = new AlumnoData(conexion);
        listaAlumno = (ArrayList)alumnoData.obtenerAlumnos();
              
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(CargarNotas.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMENUDESPLEGABLE = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCursada = new javax.swing.JTable();
        jGUARDAR = new javax.swing.JButton();
        jCANCELAR = new javax.swing.JButton();

        jLabel1.setText("Cargar Notas");

        jLabel2.setText("Alumnos");

        jtCursada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtCursada);

        jGUARDAR.setText("Guardar");

        jCANCELAR.setText("Cancelar");
        jCANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCANCELARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(85, 85, 85)
                        .addComponent(jMENUDESPLEGABLE, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jGUARDAR)
                .addGap(43, 43, 43)
                .addComponent(jCANCELAR)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jMENUDESPLEGABLE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGUARDAR)
                    .addComponent(jCANCELAR))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCANCELARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCANCELARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCANCELAR;
    private javax.swing.JButton jGUARDAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<Alumno> jMENUDESPLEGABLE;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtCursada;
    // End of variables declaration//GEN-END:variables
}
